//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class edit_recipe
    {
        protected global::System.Web.UI.WebControls.Panel MessagePanel;
        protected global::System.Web.UI.WebControls.Label MessageLabel;
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Label ErrorLabel;
        protected global::System.Web.UI.WebControls.Panel FormPanel;
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected global::System.Web.UI.WebControls.TextBox RecipeName;
        protected global::System.Web.UI.WebControls.DropDownList CuisineType;
        protected global::System.Web.UI.WebControls.DropDownList Difficulty;
        protected global::System.Web.UI.WebControls.TextBox CookingTime;
        protected global::System.Web.UI.WebControls.TextBox Servings;
        protected global::System.Web.UI.WebControls.FileUpload RecipeImage;
        protected global::System.Web.UI.WebControls.TextBox RecipeVideo;
        protected global::System.Web.UI.WebControls.TextBox RecipeDescription;
        protected global::System.Web.UI.WebControls.TextBox CookingIngredient;
        protected global::System.Web.UI.WebControls.TextBox CookingInstruction;
        protected global::System.Web.UI.WebControls.TextBox Calory;
        protected global::System.Web.UI.WebControls.TextBox Protein;
        protected global::System.Web.UI.WebControls.TextBox Carb;
        protected global::System.Web.UI.WebControls.TextBox Fat;
        protected global::System.Web.UI.WebControls.DropDownList RecipeStatus;
        protected global::System.Web.UI.WebControls.Button SaveBtn;
    }
}
