//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class edit_event
    {
        protected global::System.Web.UI.WebControls.Panel FormPanel;
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected global::System.Web.UI.WebControls.Panel EditEventPanel;
        protected global::System.Web.UI.WebControls.TextBox StartDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStartDate;
        protected global::System.Web.UI.WebControls.TextBox EndDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEndDate;
        protected global::System.Web.UI.WebControls.TextBox StartTime;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStartTime;
        protected global::System.Web.UI.WebControls.TextBox EndTime;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEndTime;
        protected global::System.Web.UI.WebControls.TextBox Location;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLocation;
        protected global::System.Web.UI.WebControls.Button SaveBtn;
    }
}
