//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class events
    {
        /// <summary>
        /// EventsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater EventsRepeater;

        /// <summary>
        /// PaginationPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PaginationPanel;

        /// <summary>
        /// PrevPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrevPageButton;

        /// <summary>
        /// PageNumbersRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater PageNumbersRepeater;

        /// <summary>
        /// NextPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button NextPageButton;

        /// <summary>
        /// TimeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList TimeFilter;

        /// <summary>
        /// EventTypeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList EventTypeFilter;

        /// <summary>
        /// SearchBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SearchBox;
    }
}
