//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{
    public partial class home : global::System.Web.UI.Page
    {
        /// <summary>
        /// HomeEventsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater HomeEventsRepeater;

        /// <summary>
        /// MessagePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        /// <summary>
        /// MessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// CuisineRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater CuisineRepeater;

        /// <summary>
        /// NoCuisinesPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel NoCuisinesPanel;
    }
}
