//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class post_event
    {

        /// <summary>
        /// MessagePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        /// <summary>
        /// MessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// ErrorLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ErrorLabel;

        /// <summary>
        /// FormPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel FormPanel;

        /// <summary>
        /// ValidationSummary1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        /// <summary>
        /// BasicInfoPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel BasicInfoPanel;

        /// <summary>
        /// EventTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EventTitle;

        /// <summary>
        /// rfvEventTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEventTitle;

        /// <summary>
        /// EventDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EventDescription;

        /// <summary>
        /// rfvEventDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEventDescription;

        /// <summary>
        /// EventImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload EventImage;

        /// <summary>
        /// rfvEventImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEventImage;

        /// <summary>
        /// EventDetailsPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel EventDetailsPanel;

        /// <summary>
        /// EventType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList EventType;

        /// <summary>
        /// rfvEventType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEventType;

        /// <summary>
        /// CuisineType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList CuisineType;

        /// <summary>
        /// rfvCuisineType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCuisineType;

        /// <summary>
        /// StartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StartDate;

        /// <summary>
        /// rfvStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStartDate;

        /// <summary>
        /// EndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EndDate;

        /// <summary>
        /// rfvEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEndDate;

        /// <summary>
        /// StartTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox StartTime;

        /// <summary>
        /// rfvStartTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStartTime;

        /// <summary>
        /// EndTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EndTime;

        /// <summary>
        /// rfvEndTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEndTime;

        /// <summary>
        /// MaxParticipant control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox MaxParticipant;

        /// <summary>
        /// rfvMaxParticipant control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMaxParticipant;

        /// <summary>
        /// rvMaxParticipant control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvMaxParticipant;

        /// <summary>
        /// Location control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Location;

        /// <summary>
        /// rfvLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLocation;

        /// <summary>
        /// EventContentPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel EventContentPanel;

        /// <summary>
        /// LearningObjectives control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox LearningObjectives;

        /// <summary>
        /// rfvLearningObjectives control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLearningObjectives;

        /// <summary>
        /// IncludedItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox IncludedItems;

        /// <summary>
        /// rfvIncludedItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIncludedItems;

        /// <summary>
        /// Requirements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Requirements;

        /// <summary>
        /// rfvRequirements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRequirements;

        /// <summary>
        /// CancelBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button CancelBtn;

        /// <summary>
        /// SubmitBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SubmitBtn;
    }
}
