//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class post_recipe
    {
        
        /// <summary>
        /// MessagePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        /// <summary>
        /// MessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// ErrorLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ErrorLabel;

        /// <summary>
        /// FormPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel FormPanel;

        /// <summary>
        /// ValidationSummary1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        /// <summary>
        /// RecipeName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox RecipeName;

        /// <summary>
        /// rfvRecipeName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRecipeName;

        /// <summary>
        /// CuisineType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList CuisineType;

        /// <summary>
        /// rfvCuisineType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCuisineType;

        /// <summary>
        /// Difficulty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Difficulty;

        /// <summary>
        /// rfvDifficulty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDifficulty;

        /// <summary>
        /// CookingTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CookingTime;

        /// <summary>
        /// rfvCookingTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCookingTime;

        /// <summary>
        /// rvCookingTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvCookingTime;

        /// <summary>
        /// Servings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Servings;

        /// <summary>
        /// rfvServings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvServings;

        /// <summary>
        /// rvServings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvServings;

        /// <summary>
        /// RecipeImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload RecipeImage;

        /// <summary>
        /// rfvRecipeImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRecipeImage;

        /// <summary>
        /// RecipeVideo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox RecipeVideo;

        /// <summary>
        /// revRecipeVideo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revRecipeVideo;

        /// <summary>
        /// RecipeDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox RecipeDescription;

        /// <summary>
        /// rfvRecipeDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRecipeDescription;

        /// <summary>
        /// CookingIngredient control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CookingIngredient;

        /// <summary>
        /// rfvCookingIngredient control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCookingIngredient;

        /// <summary>
        /// CookingInstruction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CookingInstruction;

        /// <summary>
        /// rfvCookingInstruction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCookingInstruction;

        /// <summary>
        /// Calory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Calory;

        /// <summary>
        /// Protein control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Protein;

        /// <summary>
        /// Carb control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Carb;

        /// <summary>
        /// Fat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Fat;

        /// <summary>
        /// PublishBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PublishBtn;
    }
}
