//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class recipes
    {
        /// <summary>
        /// CuisineFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList CuisineFilter;

        /// <summary>
        /// SearchBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SearchBox;

        /// <summary>
        /// RecipesRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RecipesRepeater;

        /// <summary>
        /// PaginationPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PaginationPanel;

        /// <summary>
        /// PrevPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrevPageButton;

        /// <summary>
        /// PageNumbersRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater PageNumbersRepeater;

        /// <summary>
        /// NextPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button NextPageButton;
    }
}