//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class recipe_detail
    {
        /// <summary>
        /// ReviewPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ReviewPanel;

        /// <summary>
        /// ReviewRating control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ReviewRating;

        /// <summary>
        /// ReviewComment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ReviewComment;

        /// <summary>
        /// ReviewPhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload ReviewPhoto;

        /// <summary>
        /// ReviewVideo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload ReviewVideo;

        /// <summary>
        /// SubmitReviewBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SubmitReviewBtn;

        /// <summary>
        /// ReviewError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ReviewError;

        /// <summary>
        /// ReviewFormUpdatePanel control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel ReviewFormUpdatePanel;

        /// <summary>
        /// ReviewListUpdatePanel control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel ReviewListUpdatePanel;

        /// <summary>
        /// ReviewRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater ReviewRepeater;

        /// <summary>
        /// PaginationPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PaginationPanel;

        /// <summary>
        /// PrevPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrevPageButton;

        /// <summary>
        /// PageNumbersRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater PageNumbersRepeater;

        /// <summary>
        /// NextPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button NextPageButton;

        /// <summary>
        /// NoReviewsPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel NoReviewsPanel;

        protected global::System.Web.UI.UpdatePanel ReviewUpdatePanel;

        protected global::System.Web.UI.WebControls.HiddenField RecipeIdHidden;
        

    }
}
