//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class user_bookmark
    {
        protected global::System.Web.UI.WebControls.Image UserProfileImage;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.LinkButton UserLogoutButton;

        protected global::System.Web.UI.UpdatePanel UserBookmarkUpdatePanel;
        protected global::System.Web.UI.WebControls.Panel MessagePanel;
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        protected global::System.Web.UI.WebControls.DropDownList CuisineFilter;
        protected global::System.Web.UI.WebControls.TextBox SearchBox;

        protected global::System.Web.UI.WebControls.Repeater BookmarksRepeater;

        protected global::System.Web.UI.WebControls.Panel PaginationPanel;
        protected global::System.Web.UI.WebControls.Button PrevPageButton;
        protected global::System.Web.UI.WebControls.Button NextPageButton;
        protected global::System.Web.UI.WebControls.Repeater PageNumbersRepeater;
    }
}
