//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class user_notification
    {
        /// <summary>
        /// ReadFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ReadFilter;

        /// <summary>
        /// TypeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList TypeFilter;

        /// <summary>
        /// SearchBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SearchBox;

        /// <summary>
        /// NotificationRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater NotificationRepeater;
    }
}
