//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hope
{


    public partial class user_event
    {
        /// <summary>
        /// UserProfileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image UserProfileImage;

        /// <summary>
        /// UserNameLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserNameLabel;

        /// <summary>
        /// StatusFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilter;

        /// <summary>
        /// TimeRangeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList TimeRangeFilter;

        /// <summary>
        /// SearchBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SearchBox;

        /// <summary>
        /// EventsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater EventsRepeater;

        /// <summary>
        /// PaginationPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PaginationPanel;

        /// <summary>
        /// PrevPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button PrevPageButton;

        /// <summary>
        /// NextPageButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button NextPageButton;

        /// <summary>
        /// PageNumbersRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater PageNumbersRepeater;

        /// <summary>
        /// MessagePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        /// <summary>
        /// MessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;
    }
}
